Revamp
ehsanh06/statgen pull request #2
Opened 2017-01-12 12:16 UTC by ehsanh06

I've rewritten this again - opened up a branch as revamp. Trouble I'm facing is getting the MD's to generate at the gulp post -t "title" or gulp page -t "title", despite there being no errors. 

Not sure why my views folder hasn't been pushed

2017-01-12 15:22 UTC, ehsanh06 commented
Believe to have found what's causing it --seems to be the directory that's pointing towards that's not working. I'll have to work out exactly what directory it needs to be pointed to. Reason being is because there's a lot of requires for the global js file, and I may need to move that. Would like to know what you think about it.

2017-01-13 15:01 UTC, shahidaltaf requested changes

2017-01-13 15:01 UTC, shahidaltaf commented on gulpfile.js
> +// Include Gulp and modular task file
Add 'use strict';

2017-01-13 15:01 UTC, shahidaltaf commented on gulpfile.js
> +var tasks = require('./lib/tasks/index');
This can be simply `var tasks = require('./lib/tasks/');`

2017-01-13 15:01 UTC, shahidaltaf commented on gulpfile.js
> +    console.log('Console Message: Building Post'),
The console log here is redundant. it would be better placed in the `tasks.post`

2017-01-13 15:01 UTC, shahidaltaf commented on gulpfile.js
> +    tasks.post;
`tasks.post;` doesn't call the function, it should be `tasks.post();`

2017-01-13 15:01 UTC, shahidaltaf commented on gulpfile.js
> +    tasks.post;
`tasks.post();` should take a **title** parameter, and an optional **slug**

2017-01-13 15:01 UTC, shahidaltaf commented on gulpfile.js
> +    tasks.page;
`tasks.page;` doesn't call the function, it should be `tasks.page();`

2017-01-13 15:01 UTC, shahidaltaf commented on gulpfile.js
> +    tasks.page;
Should take a title parameter

2017-01-13 15:01 UTC, shahidaltaf commented on gulpfile.js
> +    tasks.build;
`tasks.build;` doesn't call the function, it should be `tasks.build();`

2017-01-13 15:01 UTC, shahidaltaf commented on lib/global.js
> +// Include Gulp, plugins and local files
`global.js` should be renamed as `utils.js` and placed within the `tasks` folder

2017-01-13 21:57 UTC, shahidaltaf requested changes
Just a structural review and request changes. I specific code review will follow

2017-01-13 21:57 UTC, shahidaltaf commented on gulpfile.js
> +    tasks.post(title, slug);
`title` and `slug` are not declare variables in the scope of this file. Please catch command line arguments to pass into the `tasks.post(title, slug)` function

2017-01-13 21:57 UTC, shahidaltaf commented on gulpfile.js
> +    tasks.page(title);
`title` is not A declared variable in the scope of this file. Please catch command line argument to pass into the tasks.page(title) function

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/index.js
> +var post = require('./post/post');
`require('./post/post')...` are all invalid paths now as you have taken out sub folders

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/index.js
> +};
module exports can be (preferably) written as...

```
module.exports.post = require('./post');
module.exports.page = require('./page');
module.exports.build = require('./build');
```

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/page.js
> +function page() {
`function page()` needs to take a `title` argument

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/page.js
> +module.exports = {
This can be better written as `module.exports = page` as there's only one function to export

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/post.js
> +module.exports = {
This can be better written as module.exports = post as there's only one function to export

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/post.js
> +function post() {
function post() needs to take `title` and  optional `slug` arguments. These need to passed into the function and the handling of `argv.title` below needs to be revisted

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/utils.js
> +var siteData = {
This data object is very specific to the build process and should be in `build.js`

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/utils.js
> +var srcDir = {
This `srcDir` object is very specific to the build process and should be in `build.js`

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/utils.js
> +var createPage = function (data) {
This is not a utility function and is very specific to the build process and should be in `build.js`

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/utils.js
> +var build = function () {
Remove this function, it is redundant

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/utils.js
> +// Include Gulp, plugins and local files
Remove this comment

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/utils.js
> +var mkdirp = require('mkdirp');
Remove unused modules

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/utils.js
> +var setPageTitle = function (title) { return title + ' - ' + srcDir.author; };
This function is specific to `build.js`, should this be here?

2017-01-13 21:57 UTC, shahidaltaf commented on lib/tasks/utils.js
> +module.exports = {
Update the exports module to only have the refactored utility functions in

2017-01-14 15:54 UTC, shahidaltaf requested changes
Add a README.md file back in

2017-01-14 15:54 UTC, shahidaltaf commented on gulpfile.js
> +var t = title || null,
This variables make no sense being here. This should be in the context of the gulp tasks below

2017-01-14 15:54 UTC, shahidaltaf commented on gulpfile.js
> +var t = title || null,
Where is `title` declared? You've used `title` but you haven't declared it.

2017-01-14 15:54 UTC, shahidaltaf commented on gulpfile.js
> +    tasks.post(title, slug);
`title` and `slug` should be defined above this method. It's ok to hard-code some default values here for now e.g. `var title = "Post example title"`. Same with slug.

2017-01-14 15:54 UTC, shahidaltaf commented on lib/tasks/build.js
> +    srcDir: srcDir,
`srcDir` isn't a good enough object name, use full words

2017-01-14 15:54 UTC, shahidaltaf commented on lib/tasks/build.js
> +    srcDir: srcDir,
`srcDir` and `siteData` have no need to be exported. Please remove them.

2017-01-14 15:54 UTC, shahidaltaf commented on lib/tasks/index.js
> +var post = require('./post');
Remove these `var` declarations. Now redundant and unused given the changes below.

2017-01-14 15:54 UTC, shahidaltaf commented on lib/tasks/post.js
> +var build = require('./build');
`build.js` isn'n need in this task file

2017-01-14 15:54 UTC, shahidaltaf commented on lib/tasks/post.js
> +var t = title || null,
Remove these declarations here as they should come from the function call below

2017-01-14 15:54 UTC, shahidaltaf commented on lib/tasks/utils.js
> +var dirExists = function (path, err) {
For utility functions, use full words and not abbreviations

2017-01-14 15:54 UTC, shahidaltaf commented on lib/tasks/utils.js
> +        fs.statSync(path);
`fs` module isn't declared above. You must add it to use `fs` functions

2017-01-14 15:54 UTC, shahidaltaf commented on gulpfile.js
> +    s = slug ||  null;
Same as comment for `title`, please remove and put `slug in the appropriate gulp task

2017-01-14 15:54 UTC, shahidaltaf commented on gulpfile.js
> +// Default task goes here
Add a default task that simply console log out 'default task'

2017-01-14 22:40 UTC, shahidaltaf requested changes
A few minor oversights need addressing

2017-01-14 22:40 UTC, shahidaltaf commented on lib/page.js
> -        var slug = (argv.slug || argv.s) ? utils.hyphenateString(argv.slug || argv.s) : utils.hyphenateString(title.toString());
Restore this line please, you need to format a slug

2017-01-14 22:40 UTC, shahidaltaf commented on lib/page.js
> +var title, slug = "Page title example";
Delete this as it's not required

2017-01-14 22:40 UTC, shahidaltaf commented on lib/post.js
> +var title, slug = "Post title example";
Delete this line as it's not required

2017-01-14 22:40 UTC, shahidaltaf commented on gulpfile.js
> +    var title, slug = "Post title example";
Not sure why you have set `slug` to the same as the `title`. You either leave it out or set it to something specific . Keep the variables on separate lines for now

2017-01-15 17:54 UTC, merged